name: xeus-python
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - xeus=1.0.3
  - nlohmann_json
  - cppzmq
  - xtl>=0.7, <0.8
  - lua>=5.2.0
  - xwidgets>=0.25.1
  # Test dependencies
  - pytest
  - nbval
  - ipympl
  - jupyter_kernel_test
