name: xeus-lua
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - xeus>=2.0.0
  - nlohmann_json
  - cppzmq
  - xtl>=0.7, <0.8
  - lua>=5.2.0
  - openlibm # [linux]
  - xwidgets>=0.25.1
  # Test dependencies
  - pytest
  - nbval
  - ipympl
  - jupyter_kernel_test
